baseurl = "https://cagve.github.io/daemons-karu/" 
languageCode = "en-US" 
title = "daemons karu" 

paginate = 11 # Number of posts to show before paginating

# copyright = "Copyright &copy; Copyright Owner. Licensed under <a target=\"_blank\" rel=\"external noopener license\" href=\"https://creativecommons.org/licenses/by-nd/4.0/\">CC-BY-ND-4.0</a>." # Optional, remove to suppress copyright notices
publishDir="docs"

theme = [
  "fractal-forest", 
  "after-dark" 
]

disableLiveReload = false # Optional, set true to disable live reload
enableRobotsTXT = true # Suggested, enable robots.txt file
sectionPagesMenu = "main" # Enable menu system for lazy bloggers

[params.layout.home]
  hide_blog = true


[[params.layout.home.section]]
  type = "post"
  limit = 2
  weight = 3

