baseurl = "https://cagve.github.io/daemons-karu/" 
languageCode = "en-US" 
title = "daemons karu" 

paginate = 11 # Number of posts to show before paginating

# copyright = "Copyright &copy; Copyright Owner. Licensed under <a target=\"_blank\" rel=\"external noopener license\" href=\"https://creativecommons.org/licenses/by-nd/4.0/\">CC-BY-ND-4.0</a>." # Optional, remove to suppress copyright notices
publishDir="docs"

theme = [
  "fractal-forest", 
  "after-dark" 
]

[outputs]
  home = ["HTML", "RSS", "JSON"]

enableRobotsTXT = true # Suggested, enable robots.txt file
sectionPagesMenu = "main" # Enable menu system for lazy bloggers

[params.layout.home]
  hide_blog = true

[[params.layout.home.section]]
  type = "post"
  title = "post"
  limit = 2
  weight = 2

[[params.layout.home.section]]
  type = "whoami"
  title = "whoami"
  weight = 1

 
# MENÚ
[[menu.main]] 
 name = "home"
 weight = 1
 identifier = "home"
 url = "/"

[[menu.main]]
 name = "log"
 weight = 1
 identifier = "log"
 url = "/log/"

[[menu.main]]
 name = "post"
 weight = 1
 identifier = "post"
 url = "/post/"

[[menu.main]] 
 name = "whoami"
 weight = 1
 identifier = "whoami"
 url = "/whoami"

[[menu.main]]
 name = "search"
 weight = 2
 identifier = "search"
 url = "/search/"
