baseURL = "https://cagve.github.io/daemons-karu/"
languageCode = "en-us"
title = "daemons-karu"
theme="Niello" 
publishDir = "docs"

staticDir = ["static", "themes/Niello/static"]

[menu]
    [[menu.niello]]
    name = "casa"
    url = "/"
    weight = 1


